/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 arcade.glb 
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Arcade = forwardRef((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/arcade.glb`,
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={ref} name="Scene">
        <mesh
          name="Arcade_Body"
          geometry={nodes.Arcade_Body.geometry}
          material={materials.arcade_body_material}
          position={[-17.465, 0.033, -7.719]}
        >
          <mesh
            name="Arcade_Coin_Receptor"
            geometry={nodes.Arcade_Coin_Receptor.geometry}
            material={materials.arcade_secondary_material}
            position={[1.974, 0.607, 0]}
            scale={0.834}
          />
          <mesh
            name="Arcade_Joystick_Bottom"
            geometry={nodes.Arcade_Joystick_Bottom.geometry}
            material={materials.arcade_secondary_material}
            position={[2.77, 2.4, 1.21]}
            rotation={[0, 0, -0.225]}
          />
          <mesh
            name="Arcade_Screen_Frame"
            geometry={nodes.Arcade_Screen_Frame.geometry}
            material={materials.arcade_secondary_material}
            position={[1.354, 4.262, 0]}
          />
          <mesh
            name="Arcade_Sides"
            geometry={nodes.Arcade_Sides.geometry}
            material={materials.arcade_secondary_material}
            position={[-0.062, -0.016, -2.201]}
          />
        </mesh>
        <mesh
          name="Arcade_Button1_Bottom"
          geometry={nodes.Arcade_Button1_Bottom.geometry}
          material={materials.arcade_sphere_button1_material}
          position={[-14.554, 2.387, -8.279]}
          rotation={[0, 0, -0.225]}
        />
        <mesh
          name="Arcade_Button2_Bottom"
          geometry={nodes.Arcade_Button2_Bottom.geometry}
          material={materials.arcade_button2_material}
          position={[-14.803, 2.444, -9.135]}
          rotation={[0, 0, -0.225]}
        />
      </group>
    </group>
  );
});

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/arcade.glb`);

// Assign a display name to the component
Arcade.displayName = "Arcade";

export { Arcade };
