/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 arcade_joystick.glb 
*/

import React, { forwardRef, useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useAppContext } from "../context/AppContext.context"; // Import context.

const ArcadeJoystick = forwardRef((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/arcade_joystick.glb",
  );
  const { actions } = useAnimations(animations, group);

  const { setJoystickAnimationActions } = useAppContext();

  useEffect(() => {
    // Update the context with the loaded animations from this particular GLB file.
    setJoystickAnimationActions(actions);
  }, [actions, setJoystickAnimationActions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          ref={ref}
          name="Joystick"
          geometry={nodes.Joystick.geometry}
          material={materials.arcade_sphere_button1_material}
          position={[-14.694, 2.434, -6.509]}
        >
          <mesh
            name="Arcade_Joystick_Lever"
            geometry={nodes.Arcade_Joystick_Lever.geometry}
            material={materials.arcade_joystick_material}
          />
        </mesh>
      </group>
    </group>
  );
});

useGLTF.preload("./models/arcade_joystick.glb");
ArcadeJoystick.displayName = "ArcadeJoystick";

export { ArcadeJoystick };
