/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 arcade_button_a.glb 
*/

import React, { forwardRef, useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useAppContext } from "../context/AppContext.context"; // Import context.

const ArcadeButtonA = forwardRef((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/arcade_button_a.glb",
  );
  const { actions } = useAnimations(animations, group);

  const { setButtonAAnimationAction } = useAppContext();

  useEffect(() => {
    // Update the context with the loaded animations from this particular GLB file.
    setButtonAAnimationAction(actions);
  }, [actions, setButtonAAnimationAction]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          ref={ref}
          name="Arcade_Button_A"
          geometry={nodes.Arcade_Button_A.geometry}
          material={materials.arcade_button2_material}
          position={[-14.789, 2.502, -9.135]}
          rotation={[0, 0, -0.225]}
        />
      </group>
    </group>
  );
});

useGLTF.preload("./models/arcade_button_a.glb");
ArcadeButtonA.displayName = "Arcade_Button_A";

export { ArcadeButtonA };
