/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 baby_bunny_animation.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BabyBunnyAnimation({ visible, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/baby_bunny_animation.glb",
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["BabyBunny ArmatureAction"].play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BabyBunny_Armature">
          <primitive object={nodes.Root} />
          <primitive object={nodes.LegL} />
          <primitive object={nodes.LegR} />
          <group name="Baby_Bunny_Arms">
            <skinnedMesh
              name="Plane014"
              geometry={nodes.Plane014.geometry}
              material={materials["Baby Bunny Pink"]}
              skeleton={nodes.Plane014.skeleton}
            />
            <skinnedMesh
              name="Plane014_1"
              geometry={nodes.Plane014_1.geometry}
              material={materials["Baby Bunny Body Color.001"]}
              skeleton={nodes.Plane014_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="Baby_Bunny_Body"
            geometry={nodes.Baby_Bunny_Body.geometry}
            material={materials["Baby Bunny Body Color"]}
            skeleton={nodes.Baby_Bunny_Body.skeleton}
          />
          <skinnedMesh
            name="Baby_Bunny_Body001"
            geometry={nodes.Baby_Bunny_Body001.geometry}
            material={materials["Material.004"]}
            skeleton={nodes.Baby_Bunny_Body001.skeleton}
          />
          <skinnedMesh
            name="Baby_Bunny_Eyes_Open"
            geometry={nodes.Baby_Bunny_Eyes_Open.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Baby_Bunny_Eyes_Open.skeleton}
          />
          <skinnedMesh
            name="Baby_Bunny_Happy_Mouth"
            geometry={nodes.Baby_Bunny_Happy_Mouth.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Baby_Bunny_Happy_Mouth.skeleton}
          />
          <skinnedMesh
            name="Baby_Bunny_Legs"
            geometry={nodes.Baby_Bunny_Legs.geometry}
            material={materials["Baby Bunny Body Color.001"]}
            skeleton={nodes.Baby_Bunny_Legs.skeleton}
          />
          <skinnedMesh
            name="Baby_Bunny_Rosy_Cheeks"
            geometry={nodes.Baby_Bunny_Rosy_Cheeks.geometry}
            material={materials["Baby Bunny Pink"]}
            skeleton={nodes.Baby_Bunny_Rosy_Cheeks.skeleton}
          />
          <skinnedMesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["Baby Bunny Lazo"]}
            skeleton={nodes.Cube001.skeleton}
          />
          <skinnedMesh
            name="Cube003"
            geometry={nodes.Cube003.geometry}
            material={materials["Baby Bunny Lazo"]}
            skeleton={nodes.Cube003.skeleton}
          />
          <skinnedMesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials["Baby Bunny Lazo"]}
            skeleton={nodes.Cylinder.skeleton}
          />
          <skinnedMesh
            name="Nose"
            geometry={nodes.Nose.geometry}
            material={materials["Baby Bunny Pink"]}
            skeleton={nodes.Nose.skeleton}
          />
          <skinnedMesh
            name="Pestana_Baby_Bunny"
            geometry={nodes.Pestana_Baby_Bunny.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Pestana_Baby_Bunny.skeleton}
          />
          <skinnedMesh
            name="Pestana_Baby_Bunny002"
            geometry={nodes.Pestana_Baby_Bunny002.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Pestana_Baby_Bunny002.skeleton}
          />
        </group>
        <skinnedMesh
          name="BabyBunnyTongue"
          geometry={nodes.BabyBunnyTongue.geometry}
          material={materials["Material.005"]}
          skeleton={nodes.BabyBunnyTongue.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/baby_bunny_animation.glb");
