/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 baby_foxito_animation.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BabyFoxitoAnimation({ visible, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/baby_foxito_animation.glb`,
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Baby Foxito ArmatureAction"].play();
  }, [actions]);
  return (
    <group visible={visible} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Baby_Foxito_Armature">
          <primitive object={nodes.Bone} />
          <group name="Baby_Foxito_Arm_L">
            <skinnedMesh
              name="Plane023"
              geometry={nodes.Plane023.geometry}
              material={materials["Material.009"]}
              skeleton={nodes.Plane023.skeleton}
            />
            <skinnedMesh
              name="Plane023_1"
              geometry={nodes.Plane023_1.geometry}
              material={materials["Material.010"]}
              skeleton={nodes.Plane023_1.skeleton}
            />
          </group>
          <group name="Baby_Foxito_Arm_R">
            <skinnedMesh
              name="Plane015"
              geometry={nodes.Plane015.geometry}
              material={materials["Material.009"]}
              skeleton={nodes.Plane015.skeleton}
            />
            <skinnedMesh
              name="Plane015_1"
              geometry={nodes.Plane015_1.geometry}
              material={materials["Material.010"]}
              skeleton={nodes.Plane015_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="Baby_Foxito_Body"
            geometry={nodes.Baby_Foxito_Body.geometry}
            material={materials["Material.002"]}
            skeleton={nodes.Baby_Foxito_Body.skeleton}
          />
          <skinnedMesh
            name="Baby_Foxito_Head"
            geometry={nodes.Baby_Foxito_Head.geometry}
            material={materials.Material}
            skeleton={nodes.Baby_Foxito_Head.skeleton}
          />
          <skinnedMesh
            name="Baby_Foxito_Nose"
            geometry={nodes.Baby_Foxito_Nose.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Baby_Foxito_Nose.skeleton}
          />
          <skinnedMesh
            name="Baby_Foxito_Wnk_Eyes001"
            geometry={nodes.Baby_Foxito_Wnk_Eyes001.geometry}
            material={materials["SVGMat.001"]}
            skeleton={nodes.Baby_Foxito_Wnk_Eyes001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  `${import.meta.env.VITE_APP_BASE_URL}models/baby_foxito_animation.glb`,
);
