/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 easel.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";
import { RepeatWrapping } from "three";

export function Easel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/easel.glb`,
  );
  const { actions } = useAnimations(animations, group);
  const texture = useLoader(
    THREE.TextureLoader,
    `${import.meta.env.VITE_APP_BASE_URL}textures/canvas_uv.webp`,
  );
  texture.wrapT = RepeatWrapping;
  texture.repeat.set(1, -1); // Flip the texture vertically
  texture.offset.set(0, 1); // This corrects the vertical offset due to flipping
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Easel_Main"
          geometry={nodes.Easel_Main.geometry}
          material={materials.easel_material}
          position={[-27.975, 15.986, -4.254]}
          rotation={[0, 0, -0.162]}
        >
          <mesh
            name="Canvas"
            geometry={nodes.Canvas.geometry}
            material={materials.canvas_material}
            position={[-0.787, 2.9, 0]}
          >
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh
            name="Easel_Back"
            geometry={nodes.Easel_Back.geometry}
            material={materials.rails_material}
            position={[3.439, 1.577, 0]}
            rotation={[0, 0, 0.162]}
          />
          <mesh
            name="Easel_Mid"
            geometry={nodes.Easel_Mid.geometry}
            material={materials.easel_material}
          />
          <mesh
            name="Easel_Support"
            geometry={nodes.Easel_Support.geometry}
            material={materials.easel_material}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/easel.glb`);
