/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 house_structure.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function HouseStructure(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/house_structure.glb`,
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Roof_Tiles_Beam"
          geometry={nodes.Roof_Tiles_Beam.geometry}
          material={materials.roof_beams_material}
          position={[-0.944, 41.716, -2.03]}
        />
        <mesh
          name="Roof_Central_Beam"
          geometry={nodes.Roof_Central_Beam.geometry}
          material={materials.roof_beams_material}
          position={[-0.945, 41.856, -1.059]}
        />
        <mesh
          name="Roof_Tiles002"
          geometry={nodes.Roof_Tiles002.geometry}
          material={materials.tiles_material}
          position={[-22.868, 36.021, -23.565]}
          scale={[2.194, 2.369, 2.369]}
        />
        <mesh
          name="Roof_Tiles012"
          geometry={nodes.Roof_Tiles012.geometry}
          material={materials.tiles_material}
          position={[-11.974, 36.106, 21.462]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[2.194, 2.369, 2.369]}
        />
        <mesh
          name="Roof_Tiles007"
          geometry={nodes.Roof_Tiles007.geometry}
          material={materials.tiles_material}
          position={[-24.234, 31.441, 8.521]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[2.194, 2.369, 2.369]}
        />
        <mesh
          name="House_Walls"
          geometry={nodes.House_Walls.geometry}
          material={materials.house_walls_material}
          position={[-1.021, 36.389, -47.88]}
          scale={19.935}
        />
        <mesh
          name="Balcony"
          geometry={nodes.Balcony.geometry}
          material={materials.house_walls_material}
          position={[-28.339, 15.545, -0.969]}
        >
          <mesh
            name="Balcony_Door"
            geometry={nodes.Balcony_Door.geometry}
            material={materials.window_frames_material}
            position={[6.308, 2.865, -0.204]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            name="Balcony_Door_Frame"
            geometry={nodes.Balcony_Door_Frame.geometry}
            material={materials.window_frames_material}
            position={[7.121, 5.242, -0.067]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            name="Balcony_Floor_Beams"
            geometry={nodes.Balcony_Floor_Beams.geometry}
            material={materials.window_frames_material}
            position={[0.19, -2.141, 7.341]}
            scale={0.722}
          />
          <mesh
            name="Balcony_Rail"
            geometry={nodes.Balcony_Rail.geometry}
            material={materials.window_frames_material}
            position={[-2.954, 3.083, 0]}
          />
          <mesh
            name="Balcony_Roof"
            geometry={nodes.Balcony_Roof.geometry}
            material={materials.roof_beams_material}
            position={[23.982, -15.545, -5.134]}
          />
          <mesh
            name="Balcony_Roof_Beam"
            geometry={nodes.Balcony_Roof_Beam.geometry}
            material={materials.window_frames_material}
            position={[6.705, 14.75, 7.679]}
            rotation={[0, 0, 0.237]}
          />
        </mesh>
        <mesh
          name="Ladder_Rails"
          geometry={nodes.Ladder_Rails.geometry}
          material={materials.rails_material}
          position={[-10.976, 17.233, 18.199]}
        />
        <mesh
          name="Ladder_Steps"
          geometry={nodes.Ladder_Steps.geometry}
          material={materials.ladder_steps_material}
          position={[-9.343, 2.907, 16.564]}
        />
        <mesh
          name="Railing_Bottom"
          geometry={nodes.Railing_Bottom.geometry}
          material={materials.ladder_steps_material}
          position={[-0.945, 42.535, -1.059]}
        />
        <mesh
          name="Railing"
          geometry={nodes.Railing.geometry}
          material={materials.rails_material}
          position={[-0.945, 42.535, -1.059]}
        />
        <mesh
          name="Window_Frame_Big_Top"
          geometry={nodes.Window_Frame_Big_Top.geometry}
          material={materials.window_frames_material}
          position={[-1.021, 36.194, -30.439]}
          scale={19.745}
        />
        <mesh
          name="Window_Frame_Small_Bottom_2"
          geometry={nodes.Window_Frame_Small_Bottom_2.geometry}
          material={materials.window_frames_material}
          position={[-10.042, 4.707, -22.001]}
        />
        <mesh
          name="Window_Frame_Small_Bottom_1"
          geometry={nodes.Window_Frame_Small_Bottom_1.geometry}
          material={materials.window_frames_material}
          position={[7.935, 4.707, -22.001]}
        />
        <mesh
          name="Floor_Bottom"
          geometry={nodes.Floor_Bottom.geometry}
          material={materials.floor_material}
          position={[0, 0, -35]}
        />
        <mesh
          name="Floor_Top"
          geometry={nodes.Floor_Top.geometry}
          material={materials.floor_material}
          position={[-17.438, 15.493, -20]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  `${import.meta.env.VITE_APP_BASE_URL}models/house_structure.glb`,
);
