/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 laptop.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";
import { RepeatWrapping } from "three";

export function Laptop(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(`${import.meta.env.VITE_APP_BASE_URL}models/laptop.glb`);
  const { actions } = useAnimations(animations, group);

  const texture = useLoader(
    THREE.TextureLoader,
    `${import.meta.env.VITE_APP_BASE_URL}textures/laptop_screen_uv.webp`,
  );
  texture.wrapT = RepeatWrapping;
  texture.repeat.set(1, -1); // Flip the texture vertically
  texture.offset.set(0, 1); // This corrects the vertical offset due to flipping

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Laptop_Base"
          position={[8.399, 2.907, -11.461]}
          scale={1.25}
        >
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={materials.laptop_main_material}
          />
          <mesh
            name="Cube053_1"
            geometry={nodes.Cube053_1.geometry}
            material={materials.laptop_secondary_material}
          />
          <mesh
            name="Laptop_Button1"
            geometry={nodes.Laptop_Button1.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.759, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button10"
            geometry={nodes.Laptop_Button10.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.054, 0.114, 0.344]}
          />
          <mesh
            name="Laptop_Button11"
            geometry={nodes.Laptop_Button11.geometry}
            material={materials.laptop_secondary_material}
            position={[-0.698, 0.114, 0.344]}
          />
          <mesh
            name="Laptop_Button12"
            geometry={nodes.Laptop_Button12.geometry}
            material={materials.laptop_secondary_material}
            position={[-0.352, 0.114, 0.344]}
          />
          <mesh
            name="Laptop_Button13"
            geometry={nodes.Laptop_Button13.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.759, 0.114, 0.686]}
          />
          <mesh
            name="Laptop_Button15"
            geometry={nodes.Laptop_Button15.geometry}
            material={materials.laptop_secondary_material}
            position={[0.362, 0.114, 0.686]}
          />
          <mesh
            name="Laptop_Button2"
            geometry={nodes.Laptop_Button2.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.408, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button3"
            geometry={nodes.Laptop_Button3.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.054, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button4"
            geometry={nodes.Laptop_Button4.geometry}
            material={materials.laptop_secondary_material}
            position={[-0.698, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button5"
            geometry={nodes.Laptop_Button5.geometry}
            material={materials.laptop_secondary_material}
            position={[-0.352, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button6"
            geometry={nodes.Laptop_Button6.geometry}
            material={materials.laptop_secondary_material}
            position={[0, 0.114, 0]}
          />
          <mesh
            name="Laptop_Button7"
            geometry={nodes.Laptop_Button7.geometry}
            material={materials.laptop_secondary_material}
            position={[0, -0.047, 0]}
          />
          <mesh
            name="Laptop_Button8"
            geometry={nodes.Laptop_Button8.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.759, 0.114, 0.344]}
          />
          <mesh
            name="Laptop_Button9"
            geometry={nodes.Laptop_Button9.geometry}
            material={materials.laptop_secondary_material}
            position={[-1.408, 0.114, 0.344]}
          />
          <mesh
            name="Laptop_Screen_Top"
            geometry={nodes.Laptop_Screen_Top.geometry}
            material={materials.laptop_main_material}
            position={[0, 0.104, -1.147]}
            rotation={[1.215, 0, 0]}
          >
            <mesh
              name="Laptop_Screen"
              geometry={nodes.Laptop_Screen.geometry}
              position={[0, -0.006, 0]}
            >
              <meshStandardMaterial map={texture} />
            </mesh>
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/laptop.glb`);
