/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 map.glb 
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Map = forwardRef((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/map.glb`,
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          ref={ref}
          name="Map"
          geometry={nodes.Map.geometry}
          material={materials.Material}
          position={[7.135, 0.784, -7.598]}
          rotation={[-Math.PI / 2, 0, 0.43]}
          scale={1.968} // 1.968
        />
      </group>
    </group>
  );
});

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/map.glb`);

// Assign a display name to the component
Map.displayName = "Map";

export { Map };
