/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 props.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Props(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/props.glb`,
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty005" position={[8.547, 4.216, 17.767]} />
        <mesh
          name="Cactus_Pot"
          geometry={nodes.Cactus_Pot.geometry}
          material={materials.flower_pot_material}
          position={[13.458, 2.953, -20.541]}
          scale={0.697}
        >
          <mesh
            name="Cactus"
            geometry={nodes.Cactus.geometry}
            material={materials.cactus_material}
            position={[-0.012, 0.207, 0.001]}
          />
        </mesh>
        <mesh
          name="Kettle"
          geometry={nodes.Kettle.geometry}
          material={materials.kettle_material}
          position={[5.897, 3.329, -13.901]}
          rotation={[0, 0.841, 0]}
          scale={0.614}
        >
          <mesh
            name="Kettle_Lid"
            geometry={nodes.Kettle_Lid.geometry}
            material={materials.kettle_material}
            position={[0, 2.008, 0]}
          />
        </mesh>
        <group name="Cylinder002" position={[3.015, -0.051, 7.302]}>
          <mesh
            name="Cylinder060"
            geometry={nodes.Cylinder060.geometry}
            material={materials.carpet_main_material}
          />
          <mesh
            name="Cylinder060_1"
            geometry={nodes.Cylinder060_1.geometry}
            material={materials.carpet_center_material}
          />
          <mesh
            name="Cylinder060_2"
            geometry={nodes.Cylinder060_2.geometry}
            material={materials.carpet_second_material}
          />
          <mesh
            name="Cylinder060_3"
            geometry={nodes.Cylinder060_3.geometry}
            material={materials.carpet_third_material}
          />
        </group>
        <mesh
          name="Computer_Base"
          geometry={nodes.Computer_Base.geometry}
          material={materials.computer_base_main_material}
          position={[-14.203, -0.395, 7.693]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="Computer_Button1"
            geometry={nodes.Computer_Button1.geometry}
            material={materials.computer_base_buttons_material}
            position={[-0.608, 1.132, 1.388]}
            scale={0.708}
          />
          <mesh
            name="Computer_Button2"
            geometry={nodes.Computer_Button2.geometry}
            material={materials.computer_base_buttons_material}
            position={[-0.35, 1.132, 1.388]}
            scale={0.708}
          />
          <mesh
            name="Computer_Reader"
            geometry={nodes.Computer_Reader.geometry}
            material={materials.computer_base_vents_material}
            position={[0, 0.78, 1.46]}
          />
          <mesh
            name="Computer_Vents"
            geometry={nodes.Computer_Vents.geometry}
            material={materials.computer_base_vents_material}
            position={[0, 1.968, 1.409]}
          />
        </mesh>
        <group
          name="Tablet_Base"
          position={[-15.225, 3.884, 9.374]}
          rotation={[-Math.PI, 1.064, -Math.PI]}
        >
          <mesh
            name="Cube119"
            geometry={nodes.Cube119.geometry}
            material={materials.tablet_main_material}
          />
          <mesh
            name="Cube119_1"
            geometry={nodes.Cube119_1.geometry}
            material={materials.tablet__screen_material}
          />
          <mesh
            name="Tablet_Buttons"
            geometry={nodes.Tablet_Buttons.geometry}
            material={materials.tablet_buttons_material}
            position={[0, 0, 1.224]}
          />
        </group>
        <group
          name="Tablet_Stylus"
          position={[-12.602, 3.463, 7.473]}
          rotation={[0, -1.062, 0]}
        >
          <mesh
            name="Cylinder057"
            geometry={nodes.Cylinder057.geometry}
            material={materials.stylus_main_material}
          />
          <mesh
            name="Cylinder057_1"
            geometry={nodes.Cylinder057_1.geometry}
            material={materials.stylus_secondary_material}
          />
          <mesh
            name="Cylinder057_2"
            geometry={nodes.Cylinder057_2.geometry}
            material={materials.stylus__terciary_material}
          />
        </group>
        <mesh
          name="Table_Keyboard_Base"
          geometry={nodes.Table_Keyboard_Base.geometry}
          material={materials.keyboard_main_material}
          position={[-11.847, 3.429, 3.585]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="Key1"
            geometry={nodes.Key1.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-1.326, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key10"
            geometry={nodes.Key10.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-0.445, 0.324, -0.373]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key11"
            geometry={nodes.Key11.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[0, 0.324, -0.373]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key12"
            geometry={nodes.Key12.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[0.432, 0.324, -0.373]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key13"
            geometry={nodes.Key13.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-1.326, 0.27, 0.052]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key14"
            geometry={nodes.Key14.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-0.131, 0.27, 0.052]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key15"
            geometry={nodes.Key15.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[1.325, 0.27, 0.052]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key2"
            geometry={nodes.Key2.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-0.888, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key3"
            geometry={nodes.Key3.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-0.445, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key4"
            geometry={nodes.Key4.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[0, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key5"
            geometry={nodes.Key5.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[0.432, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key6"
            geometry={nodes.Key6.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[0.873, 0.379, -0.799]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key7"
            geometry={nodes.Key7.geometry}
            material={materials.computer_keyboard_enter_key_material}
            position={[1.196, 0.297, -0.511]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key8"
            geometry={nodes.Key8.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-1.326, 0.324, -0.373]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
          <mesh
            name="Key9"
            geometry={nodes.Key9.geometry}
            material={materials.computer_keyboard_keys_material}
            position={[-0.888, 0.324, -0.373]}
            rotation={[0.127, 0, 0]}
            scale={1.25}
          />
        </mesh>
        <mesh
          name="Mouse_Base"
          geometry={nodes.Mouse_Base.geometry}
          material={materials.computer_mouse_material}
          position={[-12.496, 3.27, 0.084]}
          rotation={[-Math.PI, 1.06, -Math.PI]}
          scale={0.569}
        >
          <mesh
            name="Mouse_Button1"
            geometry={nodes.Mouse_Button1.geometry}
            material={materials.computer_mouse_buttons_material}
            position={[0.477, 0.779, -0.47]}
          />
          <mesh
            name="Mouse_Button2"
            geometry={nodes.Mouse_Button2.geometry}
            material={materials.computer_mouse_buttons_material}
            position={[-0.475, 0.779, -0.47]}
          />
          <mesh
            name="Mouse_Wheel"
            geometry={nodes.Mouse_Wheel.geometry}
            material={materials.computer_mouse_wheel_material}
            position={[0, 0.728, -0.4]}
          />
        </mesh>
        <group
          name="Speaker_Base"
          position={[-15.109, 4.407, -1.081]}
          rotation={[0, -0.187, 0]}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.computer_speaker_main_material}
          />
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials.computer_speaker_secondary_material}
          />
          <mesh
            name="Speaker_Big"
            geometry={nodes.Speaker_Big.geometry}
            material={materials.computer_speaker_secondary_material}
            position={[-0.364, -0.491, 0]}
          />
          <mesh
            name="Speaker_Small"
            geometry={nodes.Speaker_Small.geometry}
            material={materials.computer_speaker_secondary_material}
            position={[0.765, 0.438, 0]}
          />
        </group>
        <mesh
          name="Arupo_Pot"
          geometry={nodes.Arupo_Pot.geometry}
          material={materials.arupo_pot_material}
          position={[-12.389, 1.601, -15.352]}
        >
          <mesh
            name="Arupo_Crown"
            geometry={nodes.Arupo_Crown.geometry}
            material={materials.arupo_foliage_material}
            position={[-0.358, 6.887, 0.753]}
          />
          <mesh
            name="Arupo_Sand"
            geometry={nodes.Arupo_Sand.geometry}
            material={materials.arupo_sand_material}
            position={[0.146, 0.768, -0.002]}
            scale={2.804}
          />
          <mesh
            name="Arupo_Trunk"
            geometry={nodes.Arupo_Trunk.geometry}
            material={materials.arupo_trunk_material}
            position={[-0.067, 5.498, 0.588]}
          />
        </mesh>
        <group
          name="Nintendo_Switch_Screen"
          position={[-7.439, 16.221, -15.269]}
        >
          <mesh
            name="Cube029"
            geometry={nodes.Cube029.geometry}
            material={materials.switch_body_material}
          />
          <mesh
            name="Cube029_1"
            geometry={nodes.Cube029_1.geometry}
            material={materials.switch_screen_material}
          />
          <mesh
            name="Nintendo_Switch_Left_Btns"
            geometry={nodes.Nintendo_Switch_Left_Btns.geometry}
            material={materials.switch_buttons_material}
          />
          <mesh
            name="Nintendo_Switch_Left_Ctrl"
            geometry={nodes.Nintendo_Switch_Left_Ctrl.geometry}
            material={materials.switch_left_ctrl_material}
          />
          <mesh
            name="Nintendo_Switch_Left_Joycon"
            geometry={nodes.Nintendo_Switch_Left_Joycon.geometry}
            material={materials.switch_buttons_material}
          />
          <mesh
            name="Nintendo_Switch_Right_Btns"
            geometry={nodes.Nintendo_Switch_Right_Btns.geometry}
            material={materials.switch_buttons_material}
          />
          <mesh
            name="Nintendo_Switch_Right_Ctrl"
            geometry={nodes.Nintendo_Switch_Right_Ctrl.geometry}
            material={materials.switch_right_ctrl_material}
          />
          <mesh
            name="Nintendo_Switch_Right_Joycon"
            geometry={nodes.Nintendo_Switch_Right_Joycon.geometry}
            material={materials.switch_buttons_material}
          />
        </group>
        <mesh
          name="Flower_Pot1"
          geometry={nodes.Flower_Pot1.geometry}
          material={materials.flower_pot_material}
          position={[3.61, 17.312, -15.867]}
          scale={1.315}
        >
          <mesh
            name="Flower1_Leaf1"
            geometry={nodes.Flower1_Leaf1.geometry}
            material={materials.leaves_material}
            position={[-0.869, 1.774, 0.098]}
            rotation={[0, 0.071, 0]}
          />
          <mesh
            name="Flower1_Leaf2"
            geometry={nodes.Flower1_Leaf2.geometry}
            material={materials.leaves_material}
            position={[0.013, 0.65, 0.003]}
            rotation={[-0.028, 0.98, -0.157]}
          />
          <mesh
            name="Flower1_Leaf3"
            geometry={nodes.Flower1_Leaf3.geometry}
            material={materials.leaves_material}
            position={[0.035, 0.446, 0.011]}
            rotation={[-0.087, -0.816, 0.067]}
          />
          <mesh
            name="Flower1_Leaf4"
            geometry={nodes.Flower1_Leaf4.geometry}
            material={materials.leaves_material}
            position={[0.015, 0.765, 0.001]}
            rotation={[-2.865, -1.347, -2.885]}
          />
          <mesh
            name="Flower1_Leaf5"
            geometry={nodes.Flower1_Leaf5.geometry}
            material={materials.leaves_material}
            position={[0.019, 0.573, 0.028]}
            rotation={[-3.076, -0.424, -2.984]}
          />
          <mesh
            name="Flower1_Leaf6"
            geometry={nodes.Flower1_Leaf6.geometry}
            material={materials.leaves_material}
            position={[0.045, 0.35, -0.026]}
            rotation={[3, 1.307, Math.PI]}
          />
          <mesh
            name="Flower1_Leaf7"
            geometry={nodes.Flower1_Leaf7.geometry}
            material={materials.leaves_material}
            position={[0.045, 0.018, -0.026]}
            rotation={[3.094, 0.676, 3.034]}
          />
          <mesh
            name="Flower1_Leaf8"
            geometry={nodes.Flower1_Leaf8.geometry}
            material={materials.leaves_material}
            position={[0.045, 0.119, -0.026]}
            rotation={[3.086, -0.845, 2.963]}
          />
          <mesh
            name="Flower1_Sand001"
            geometry={nodes.Flower1_Sand001.geometry}
            material={materials.sand_material}
            position={[-0.019, 0.089, -0.009]}
            scale={1.045}
          />
          <mesh
            name="Stem1"
            geometry={nodes.Stem1.geometry}
            material={materials.stem_material}
            position={[0.017, -0.886, -0.026]}
          />
        </mesh>
        <mesh
          name="Flower_Pot2"
          geometry={nodes.Flower_Pot2.geometry}
          material={materials.flower_pot_material}
          position={[13.541, 1.382, 16.39]}
          scale={1.374}
        >
          <mesh
            name="Flower2_Leaf1"
            geometry={nodes.Flower2_Leaf1.geometry}
            material={materials.leaves_material}
            position={[-0.465, 1.827, -0.137]}
            rotation={[-0.294, -0.634, -0.83]}
          />
          <mesh
            name="Flower2_Leaf2"
            geometry={nodes.Flower2_Leaf2.geometry}
            material={materials.leaves_material}
            position={[-0.406, 1.882, 0.069]}
            rotation={[0.339, 0.174, -0.706]}
          />
          <mesh
            name="Flower2_Leaf3"
            geometry={nodes.Flower2_Leaf3.geometry}
            material={materials.leaves_material}
            position={[-0.173, 0.227, -0.05]}
            rotation={[-3.113, -1.099, 2.406]}
          />
          <mesh
            name="Flower2_Leaf4"
            geometry={nodes.Flower2_Leaf4.geometry}
            material={materials.leaves_material}
            position={[-0.195, -0.008, -0.001]}
            rotation={[0.005, 0.825, -0.587]}
          />
          <mesh
            name="Flower2_Leaf5"
            geometry={nodes.Flower2_Leaf5.geometry}
            material={materials.leaves_material}
            position={[-0.076, -0.118, -0.009]}
            rotation={[-3.128, 0.43, 2.601]}
          />
          <mesh
            name="Flower2_Sand"
            geometry={nodes.Flower2_Sand.geometry}
            material={materials.sand_material}
          />
          <mesh
            name="Stem2"
            geometry={nodes.Stem2.geometry}
            material={materials.stem_material}
            position={[-0.075, -0.354, -0.025]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/props.glb`);
