/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 television.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Television(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    `${import.meta.env.VITE_APP_BASE_URL}models/television.glb`,
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Television_Body"
          geometry={nodes.Television_Body.geometry}
          material={materials.television_body_material}
          position={[-8.614, 18.22, -9.792]}
        >
          <mesh
            name="television_antena"
            geometry={nodes.television_antena.geometry}
            material={materials.television_antena_material}
          />
          <mesh
            name="Television_Antena_Base"
            geometry={nodes.Television_Antena_Base.geometry}
            material={materials.television_secondary_material}
          />
          <mesh
            name="Television_Base"
            geometry={nodes.Television_Base.geometry}
            material={materials.television_body_material}
          />
          <mesh
            name="Television_Knobs"
            geometry={nodes.Television_Knobs.geometry}
            material={materials.television_secondary_material}
            scale={0.114}
          />
          <mesh
            name="Television_Screen_Frame"
            geometry={nodes.Television_Screen_Frame.geometry}
            material={materials.television_secondary_material}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.VITE_APP_BASE_URL}models/television.glb`);
