/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 text_one.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TextOne(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/text_one.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={materials["Material.003"]}
          position={[32.323, -0.485, 19.514]}
          rotation={[0, Math.PI / 2, 0]}
          scale={9.908}
        />
        <mesh
          name="Text001"
          geometry={nodes.Text001.geometry}
          material={materials["Material.003"]}
          position={[-19.783, -0.485, 31.809]}
          scale={8.932}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/text_one.glb");
