/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 text.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export function Text(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/text.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={new MeshStandardMaterial({ color: "#FECFBC" })}
          position={[29.597, -0.485, 19.514]}
          rotation={[0, Math.PI / 2, 0]}
          scale={9.908}
        />
        <mesh
          name="Text001"
          geometry={nodes.Text001.geometry}
          material={new MeshStandardMaterial({ color: "#FECFBC" })}
          position={[-19.783, -0.485, 28.813]}
          scale={8.932}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/text.glb");
